Clean up old unused parts of the release
 - bump bbs cfhttp cflager clock consuladapter diego-stress-tests fezzik lager locket runtimeschema gvt bbs cf-test-helpers cf_http consuladapter diego-stress-tests fezzik locket dropsonde gunk sonde-go protobuf clock lager go.uuid godep net
 - add new pusher
 - add new orchestrator
 - update fezzik dependencies
 - delete garden tests
 - delete old stress tests
 - update cf/golang blobs
 - update manifest generation so that it works generically

Submodule src/code.cloudfoundry.org/bbs 0000000...9314c42 (new submodule)
Submodule src/code.cloudfoundry.org/cfhttp 0000000...9f848b8 (new submodule)
Submodule src/code.cloudfoundry.org/cflager 0000000...3b0406d (new submodule)
Submodule src/code.cloudfoundry.org/clock 0000000...da82951 (new submodule)
Submodule src/code.cloudfoundry.org/consuladapter 0000000...cec33a3 (new submodule)
Submodule src/code.cloudfoundry.org/diego-stress-tests 0000000...b558a4f (new submodule)
Submodule src/code.cloudfoundry.org/fezzik 0000000...162b1a9 (new submodule)
Submodule src/code.cloudfoundry.org/lager 0000000...62951a8 (new submodule)
Submodule src/code.cloudfoundry.org/locket 0000000...eb32dc4 (new submodule)
Submodule src/code.cloudfoundry.org/runtimeschema 0000000...eed404e (new submodule)
Submodule src/github.com/FiloSottile/gvt 0000000...02e2422 (new submodule)
Submodule src/github.com/cloudfoundry/dropsonde 0000000...3899ece (new submodule)
Submodule src/github.com/cloudfoundry/sonde-go 0000000...27b0c70 (new submodule)
Submodule src/github.com/gogo/protobuf 2093b57..5d45959 (rewind):
  < fixed another fuzz test
  < fuzz tests found unchecked errors
  < fixed some fuzz tests
  < more exposed methods in the generator
  < Merge pull request #104 from ceram1/comment-from-ext
  < merge 535a10468679b4cf155f6a7afdf53b554633fc09 from golang/protobuf
  < made protoc-gen-gogo also use the vanity/command like all the other commands
  < moved protoc-gen-combo and protoc-min-version and the version library to the root
  < gostring prints less nil values
  < Merge branch 'master' into oneof
  < print out seeds for failing size tests
  < oneof: customname is starting to work
  < oneof: casttype is starting to work
  < oneof: proto3 marshalling fixed
  < all the shadows
  < vet shadow
  < vet
  < oneof: dont check errors that are always nil
  < oneof: more tests and customtype is starting to work
  < oneof: proto3 marshal fix
  < oneof: fixed populate maxfield bug
  < print out seed for failing tests
  < oneof: better wireType errors and verbose equal fix
  < merge 1dceb1a2654bdc74ca97ad91f71f500eecc96269 from golang/protobuf
  < merge 6a514e697ffedcf5d6164f65cb159cf58602c599 from golang/protobuf
  < merge 9fa1be771c31716598ee886c52af380246058132 from golang/protobuf
  < merge 483e329c7aa200b7e10dcd9cf3aa513fb77c1d01 from golang/protobuf
  < merge ef197e1a5f817199945aa5c661145b2c5f4b963f from golang/protobuf
  < merge 61b9593c6ea6768fd683086d347fb6196deb08a2 from golang/protobuf
  < merge a57d29119a1033efed1843acbb96f5d6bc4ce9a0 from golang/protobuf
  < merge 73ca790d138754f6ea69987ab1edfc80efa53905 from golang/protobuf
Submodule src/github.com/satori/go.uuid 0000000...0aa62d5 (new submodule)
Submodule src/github.com/tools/godep 0000000...3c0ccb9 (new submodule)
Submodule src/golang.org/x/net 0000000...4d38db7 (new submodule)

[#126524873]

Signed-off-by: Anoop Gopalakrishnan <agopalakrishnan@pivotal.io>

diff --git a/scripts/generate-deployment-manifest b/scripts/generate-deployment-manifest
--- a/scripts/generate-deployment-manifest
+++ b/scripts/generate-deployment-manifest
@@ -4,62 +4,109 @@ set -e
 
 manifest_generation=$(dirname $0)/../manifest-generation
 
-function usage() {
-  >&2 echo "    Usage:
-    $0 /path/to/stub/director-uuid.yml \\
-       /path/to/stub/property-overrides.yml \\
-       /path/to/stub/instance-count-overrides.yml \\
-       /path/to/stub/iaas-settings.yml \\
-       /path/to/deployment-manifests
+usage() {
+  >&2 cat <<EOF
+SYNOPSIS:
+    Generate a manifest for a Diego Perf deployment to accompany an existing CF/Diego deployment.
 
-    Ex:
-    $0 ~/deployments/bosh-lite/director.yml \\
-       manifest-generation/bosh-lite-stubs/property-overrides.yml \\
-       manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \\
-       manifest-generation/bosh-lite-stubs/iaas-settings.yml \\
-       ~/deployments/bosh-lite
-"
+USAGE:
+    $0 <MANDATORY ARGUMENTS> [OPTIONAL ARGUMENTS]
+
+MANDATORY ARGUMENTS:
+    -c <cf-path>        Path to CF manifest file.
+    -d <diego-path>     Path to Diego manifest file.
+    -i <iaas-path>      Path to IaaS-settings stub file.
+    -p <property-path>  Path to property-overrides stub file.
+
+OPTIONAL ARGUMENTS:
+    -n <count-path>     Path to instance-count-overrides stub file.
+
+EXAMPLE:
+    $0 \\
+      -c ../cf-release/bosh-lite/deployments/cf.yml \\
+      -d ../diego-release/bosh-lite/deployments/diego.yml \\
+      -i manifest-generation/bosh-lite-stubs/iaas-settings.yml \\
+      -p manifest-generation/bosh-lite-stubs/property-overrides.yml \\
+      -n manifest-generation/bosh-lite-stubs/instance-count-overrides.yml
+EOF
   exit 1
 }
 
-director_uuid=$1
-properties=$2
-instance_counts=$3
-iaas_settings=$4
-deployments=$5
+base_releases="${manifest_generation}/base-releases.yml"
+instance_counts=""
 
-if [ -z "${deployments}" ]; then
-  >&2 echo "Not enough arguments"
-  usage
+while getopts "c:i:p:n:k:v:s:d:krbgx" opt; do
+  case $opt in
+    c)
+      cf_deployment_manifest=$OPTARG
+      ;;
+    d)
+      diego_deployment_manifest=$OPTARG
+      ;;
+    i)
+      iaas_settings=$OPTARG
+      ;;
+    p)
+      property_overrides=$OPTARG
+      ;;
+    n)
+      instance_counts=$OPTARG
+      ;;
+    *)
+      echo "Unknown arguments"
+      usage
+      ;;
+  esac
+done
+
+if [ -z ${cf_deployment_manifest} ]; then
+  >&2 echo "ERROR: CF manifest file is missing"
+  argument_error=true
+else
+  if [ ! -f "${cf_deployment_manifest}" ]; then
+    >&2 echo "ERROR: CF manifest '${cf_deployment_manifest}' is not a regular file"
+    argument_error=true
+  fi
 fi
 
-if [ ! -z "$6" ]; then
-  >&2 echo "Too many arguments"
-  usage
+if [ -z ${diego_deployment_manifest} ]; then
+  >&2 echo "ERROR: Diego manifest file is missing"
+  argument_error=true
+else
+  if [ ! -f "${diego_deployment_manifest}" ]; then
+    >&2 echo "ERROR: CF manifest '${diego_deployment_manifest}' is not a regular file"
+    argument_error=true
+  fi
 fi
 
-if [ ! -f "${director_uuid}" ]; then
-  >&2 echo "Director UUID stub '${director_uuid}' is not a regular file"
-  usage
+if [ -z ${iaas_settings} ]; then
+  >&2 echo "ERROR: IaaS-settings stub file is missing"
+  argument_error=true
+else
+  if [ ! -f "${iaas_settings}" ]; then
+    >&2 echo "ERROR: IaaS Setting stub '${iaas_settings}' is not a regular file"
+    argument_error=true
+  fi
 fi
 
-if [ ! -f "${properties}" ]; then
-  >&2 echo "Property Overrides stub '${properties}' is not a regular file"
-  usage
+if [ -z ${property_overrides} ]; then
+  >&2 echo "ERROR: Property-overrides stub file is missing"
+  argument_error=true
+
+else
+  if [ ! -f "${property_overrides}" ]; then
+    >&2 echo "ERROR: Property-overrides stub '${property_overrides}' is not a regular file"
+    argument_error=true
+  fi
 fi
 
-if [ ! -f "${instance_counts}" ]; then
-  >&2 echo "Instance Count Overrides stub '${instance_counts}' is not a regular file"
-  usage
+if [[ ! -z "${instance_counts}" && ! -f "${instance_counts}" ]]; then
+  >&2 echo "ERROR: Instance-count-overrides stub '${instance_counts}' is not a regular file"
+  argument_error=true
 fi
 
-if [ ! -f "${iaas_settings}" ]; then
-  >&2 echo "IaaS Setting stub '${iaas_settings}' is not a regular file"
-  usage
-fi
-
-if [ ! -d "${deployments}" ]; then
-  >&2 echo "Deployments directory '${deployments}' is not a directory"
+if [ ! -z $argument_error ]; then
+  echo
   usage
 fi
 
@@ -68,18 +115,24 @@ tmpdir=$(mktemp -d /tmp/diego-manifest.XXXXX)
 spiff merge \
   ${manifest_generation}/config-from-cf.yml \
   ${manifest_generation}/config-from-cf-internal.yml \
-  ${deployments}/cf.yml \
+  ${cf_deployment_manifest} \
   > ${tmpdir}/config-from-cf.yml
 
 spiff merge \
+  ${manifest_generation}/config-from-diego.yml \
+  ${manifest_generation}/config-from-diego-internal.yml \
+  ${diego_deployment_manifest} \
+  > ${tmpdir}/config-from-diego.yml
+
+spiff merge \
   ${manifest_generation}/perf.yml \
-  ${properties} \
+  ${property_overrides} \
   ${instance_counts} \
   ${iaas_settings} \
   ${tmpdir}/config-from-cf.yml \
+  ${tmpdir}/config-from-diego.yml \
   > ${tmpdir}/perf.yml
 
 spiff merge \
   ${manifest_generation}/misc-templates/bosh.yml \
-  ${director_uuid} \
   ${tmpdir}/perf.yml
